planners:
  - name: 'GlobalPlanner'
    type: 'global_planner/GlobalPlanner'

controllers:
  - name: 'TebLocalPlannerROS'
    type: 'teb_local_planner/TebLocalPlannerROS'

planner_frequency:    5.0            # 全局规划器的执行频率
planner_patience:     3.0            # 在路径规划操作执行前, 全局规划器等待有效路径请求的时间
planner_max_retries:  1 


controller_frequency:   10.0           # 向底盘控制移动话题发布命令的频率
controller_patience:    15.0           # 在空间清理操作执行前, 控制器等待有效控制命令发送的时间
controller_max_retries: 1

recovery_enabled: true
recovery_patience: 10.0

oscillation_timeout:  5.0            # 执行修复机制之前, 允许震荡的时间
oscillation_distance: 0.2            # 来回运动在多大距离之上不会被认为是震荡

force_stop_at_goal: true
controller_lock_costmap: false





