global_costmap:
  global_frame: odom                    # 里程计坐标系
  robot_base_frame: base_link           # 机器人基坐标系

  update_frequency: 10.0                # 局部代价地图更新频率, 设置的大一点
  publish_frequency: 10.0               # 局部代价地图发布频率, 设置的大一点

  static_map: false                     # 
  rolling_window: true                  # 始终保证机器人在当前局部地图中心的位置
  width: 3.0                            # 宽度, 米
  height: 3.0                           # 高度, 米
  esolution: 0.05                       # 分辨率
  transform_tolerance: 0.5              # 坐标系间的转换可以忍受的最大延时

  plugins:
      - {name: obstacle_layer,     type: "costmap_2d::VoxelLayer"}
      - {name: inflation_layer,    type: "costmap_2d::InflationLayer"}