shutdown_costmaps: false             #move_base空闲时会关闭costmap

controller_frequency: 10.0           # 向底盘控制移动话题发布命令的频率
controller_patience:  15.0           # 在空间清理操作执行前, 控制器等待有效控制命令发送的时间

planner_frequency:    5.0            # 全局规划器的执行频率
planner_patience:     7.0            # 在路径规划操作执y行前, 全局规划器等待有效路径请求的时间

oscillation_timeout:  10.0           # 执行修复机制之前, 允许震荡的时间
oscillation_distance: 0.2            # 来回运动在多大距离之上不会被认为是震荡

base_global_planner:  global_planner/GlobalPlanner
base_local_planner:   teb_local_planner/TebLocalPlannerROS

# 设置恢复行为(自定义流程)
recovery_behaviors:
  - name: 'rotate_recovery'
    type: 'rotate_recovery/RotateRecovery'
  - name: 'reset_recovery'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'

reset_recovery:
  invert_area_to_clear: false       # false清除正方形外, true清除正方形内
  reset_distance: 0.2               # 以机器人为中心, reset_distance为边长设置正方形, 正方形外的障碍物清除
  layer_names: ['obstacle_layer']







