scan_filter_chain:
- name: box_filter
  type: laser_filters/LaserScanBoxFilter
  params:
    box_frame: livox_frame
    max_x: 0.1
    max_y: 0.35
    max_z: 1
    min_x: -0.35
    min_y: -0.35
    min_z: -0.1
    invert: false
