local_costmap:
  global_frame: map                     # 地图坐标系
  robot_base_frame: base_link           # 机器人基坐标系

  update_frequency:  5.0                # 局部代价地图更新频率, 设置的大一点
  publish_frequency: 5.0               # 局部代价地图发布频率, 设置的大一点

  rolling_window: true                  # 始终保证机器人在当前局部地图中心的位置
  width: 4.0                            # 宽度, 米
  height: 4.0                           # 高度, 米
  resolution: 0.05                       # 分辨率
  transform_tolerance: 0.5              # 坐标系间的转换可以忍受的最大延时

  plugins:
      - {name: obstacle_layer,     type: "costmap_2d::VoxelLayer"}
      - {name: inflation_layer,    type: "costmap_2d::InflationLayer"}