obstacle_layer: 
  enabled: true
  max_obstacle_height: 2
  min_obstacle_height: 0
  obstacle_range: 20 # 用于障碍物探测，比如: 值为 3.0，意味着检测到距离小于 3 米的障碍物时，就会引入代价地图
  raytrace_range: 20 # 用于清除障碍物，比如：值为 3.5，意味着清除代价地图中 3.5 米以外的障碍物
robot_radius: 0.32 # 0.24
inflation_radius: 0.25 # 0.15 
track_unknown_space: false

observation_sources: laserscan_filter
laserscan_filter: {data_type: LaserScan, topic: /scan, marking: true, clearing: true}