# open_base:
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 100

    left_front_joint_velocity_controller:
        type: velocity_controllers/JointVelocityController
        joint: wheel_left_front_joint
        pid: {p: 0.001, i: 0.0, d: 0.0}

    right_front_joint_velocity_controller:
        type: velocity_controllers/JointVelocityController
        joint: wheel_right_front_joint
        pid: {p: 0.001, i: 0.0, d: 0.0}

    left_rear_joint_velocity_controller:
        type: velocity_controllers/JointVelocityController
        joint: wheel_left_rear_joint
        pid: {p: 0.001, i: 0.0, d: 0.0}

    right_rear_joint_velocity_controller:
        type: velocity_controllers/JointVelocityController
        joint: wheel_right_rear_joint
        pid: {p: 0.001, i: 0.0, d: 0.0}
