global_costmap:
  plugins:
    - { name: static_layer,    type: "costmap_2d::StaticLayer"    }
    # - { name: obstacle_layer,  type: "costmap_2d::ObstacleLayer"  }
    # - { name: voronoi_layer,   type: "costmap_2d::VoronoiLayer"   }
    - { name: inflation_layer, type: "costmap_2d::InflationLayer" }

  track_unknown_space: false
  global_frame: map
  robot_base_frame: base_link
  footprint: [[0.1, 0.1], [-0.1, 0.1], [-0.1, -0.1], [0.1, -0.1], [0.1, 0.1]]
  footprint_padding: 0.05

  update_frequency: 2.0
  publish_frequency: 1.0
  transform_tolerance: 0.5

  rolling_window: false
  always_send_full_costmap: false
  resolution: 0.05

  static_layer:
    map_topic: /map
    track_unknown_space: false
    lethal_cost_threshold: 50

  # obstacle_layer:
  #   observation_sources: 3dscan 
  #   3dscan: { 
  #     sensor_frame: livox_mid360, 
  #     data_type: PointCloud2, 
  #     topic: /terrain_map, 
  #     obstacle_range: 6.0, 
  #     raytrace_range: 6.5, 
  #     marking: true, 
  #     clearing: true, 
  #     min_obstacle_height: 0, 
  #     max_obstacle_height: 0.4 
  #   }
  #   track_unknown_space: false
  #   inflation_option: 3

  inflation_layer:
    inflation_radius: 0.2
    cost_scaling_factor: 2.61

local_costmap:
  plugins:
    - { name: obstacle_layer,  type: "costmap_2d::ObstacleLayer"  }
    - { name: inflation_layer, type: "costmap_2d::InflationLayer" }

  global_frame: map
  robot_base_frame: base_link
  footprint: [[0.1, 0.1], [-0.1, 0.1], [-0.1, -0.1], [0.1, -0.1], [0.1, 0.1]]
  footprint_padding: 0.0

  update_frequency: 5.0
  publish_frequency: 1.0
  transform_tolerance: 0.5

  rolling_window: true
  width: 6
  height: 6
  resolution: 0.05

  obstacle_layer:
    observation_sources: 3dscan 
    3dscan: { 
      sensor_frame: livox_mid360, 
      data_type: PointCloud2, 
      topic: /terrain_map, 
      obstacle_range: 6.0, 
      raytrace_range: 6.5, 
      marking: true, 
      clearing: true, 
      min_obstacle_height: 0, 
      max_obstacle_height: 0.4 
    }
    track_unknown_space: false
    inflation_option: 3

  inflation_layer:
    inflation_radius: 0.15
    cost_scaling_factor: 2.61