small_gicp:
  num_threads: 4
  num_neighbors: 10
  global_leaf_size: 0.25          # 0.3 0.1 600000 slow
  registered_leaf_size: 0.1
  max_dist_sq: 1.0

  map_frame: map
  odom_frame: odom
  base_frame: base_link
  lidar_frame: livox_mid360
  prior_pcd_file: /home/jgy/RMUC_simulation/src/sentry_localization/PCD/scans.pcd     #一定要在map目录下

  pcd_in_topic: /cloud_registered
  initialpose_topic: /initialpose

  x: 5.854596
  y: 7.997880
  z: 0.0
  roll: -0.000001
  pitch: 0.000072
  yaw: 0.35