small_gicp:
  debug: false

  num_threads: 4
  num_neighbors: 10
  global_leaf_size: 0.25
  registered_leaf_size: 0.1
  max_dist_sq: 1.0

  map_frame: map
  odom_frame: odom
  base_frame: base_link
  lidar_frame: livox_mid360

  prior_pcd_file: /home/jgy/RMUC_simulation/src/sentry_localization/PCD/rmuc_2024.pcd
  pcd_in_topic: /cloud_registered
  initialpose_topic: /initialpose

  # the transform between map and odom when mapping using lio
  x:     6.881396
  y:     6.052823
  z:     0.140688
  roll:  0.000000
  pitch: 0.000000
  yaw:   1.570796327

  # 注意时间戳的问题, 目前还有问题， 虽然不会影响正常运动
  transform_tolerance: 0.1      
  registration_frequency: 10
  pose_update_frequency: 4